# Spring Boot Application Properties

# Updated Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/emutuelle
spring.datasource.username=postgres
spring.datasource.password=Dellon@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.org.springframework.orm.jpa=debug
logging.level.org.springframework.data.jpa=debug
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

# Exclude unused auto-configurations
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.data.neo4j.Neo4jRepositoriesAutoConfiguration,\
  org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration,\
  org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration,\
  org.springframework.boot.autoconfigure.netty.NettyAutoConfiguration

# Application Name
spring.application.name=emutuelle

# Server Port
server.port=8080